FROM arm32v6/python:3.9-alpine AS base

RUN echo "Building base image"
RUN apk update
RUN apk add python3-dev \
            gcc \
            libc-dev \
            libffi-dev
RUN python -m venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

## add and install requirements
RUN pip install --upgrade pip


# test stage
FROM base AS test

RUN echo "Building test image"

COPY --from=base /opt/venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /usr/src/

COPY config/requirements/test.txt .

RUN pip3 install -r test.txt

# add sensor_api app
COPY sensor_api/ sensor_api/
COPY tests/ tests/
COPY pytest.ini .


RUN flake8 --ignore=E402
