FROM arm32v6/python:3.9-alpine AS base

RUN echo "Building base image"
RUN apk update
RUN apk add python3-dev \
            gcc \
            libc-dev \
            libffi-dev
RUN python3 -m venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

## add and install requirements
RUN pip3 install --upgrade pip

# develop stage
FROM base AS dev

RUN echo "Building development image"

COPY --from=base /opt/venv /opt/venv

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /usr/src/

COPY config/requirements/base.txt .
COPY config/requirements/dev.txt .

RUN pip3 install -r dev.txt

EXPOSE 5000

# add sensor_api app
COPY sensor_api/ sensor_api/


CMD ["flask", "--app", "sensor_api.flask_app","--debug", "run", "--host=0.0.0.0"]
