name: Build and publish Docker Prod Image CI

on:
  push:
    branches: [ "main" ]

jobs:
        
  build_and_push_prod_image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and publish prod image to docker hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Docker/Dockerfile.prod
        push: true
        tags: sdpproj/sensorapi:latest
