name: Docker Dev Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build test image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Dockerfile.test
          push: false
          tags: sdpproj/sensorapi:test
        
  build_and_push_dev_image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Docker/Dockerfile.dev
        push: true
        tags: sdpproj/sensorapi:dev
